title: B*
logo: /assets/img/bstar.png
email: bstarfellowship@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Brown Startup Fellowship
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: b-star-fellowship 

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed


